// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dev} from '../models';

export function Calculate():Promise<void>;

export function EmitStateChanged():Promise<void>;

export function Export(arg1:main.ExportType):Promise<void>;

export function GetRecords():Promise<Array<any>>;

export function GetState():Promise<dev.AppState>;

export function GetVersion():Promise<string>;

export function Navigate(arg1:string):Promise<void>;

export function OnTyping(arg1:string):Promise<void>;
