// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate() {
  return window['go']['main']['App']['Calculate']();
}

export function EmitStateChanged() {
  return window['go']['main']['App']['EmitStateChanged']();
}

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function GetRecords() {
  return window['go']['main']['App']['GetRecords']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function OnTyping(arg1) {
  return window['go']['main']['App']['OnTyping'](arg1);
}
